import turtle
import colorsys
screen = turtle.Screen()
screen.setup(width=1926, height=1080)
screen.bgcolor("black")

a = turtle.Turtle()
b = turtle.Turtle()
c = turtle.Turtle()
d = turtle.Turtle()
e = turtle.Turtle()

a.pensize(1)
a.hideturtle()
a.speed(0)
b.pensize(1)
b.hideturtle()
b.speed(0)
c.pensize(1)
c.hideturtle()
c.speed(0)
d.pensize(1)
d.hideturtle()
d.speed(0)
e.pensize(1)
e.hideturtle()
e.speed(0)

a.penup(); a.goto(400,200); a.pendown()
b.penup(); b.goto(-400,200); b.pendown()
c.penup(); c.goto(400,-200); c.pendown()
d.penup(); d.goto(-400,-200); d.pendown()
o = 0.001
for i in range(180):
    e.color(colorsys.hsv_to_rgb(o,1,1))
    e.right(i)
    e.circle(60,i)
    e.forward(i)
    e.left(92)
    e.backward(i)
    e.left(92)
    a.color(colorsys.hsv_to_rgb(o,1,1))
    a.right(i)
    a.circle(60,i)
    a.forward(i)
    a.left(60)
    a.backward(i)
    a.left(60)
    b.color(colorsys.hsv_to_rgb(o,1,1))
    b.right(i)
    b.circle(60,i)
    b.forward(i)
    b.left(40)
    b.backward(i)
    b.left(40)
    c.color(colorsys.hsv_to_rgb(o,1,1))
    c.right(i)
    c.circle(60,i)
    c.forward(i)
    c.left(120)
    c.backward(i)
    c.left(120)
    d.color(colorsys.hsv_to_rgb(o,1,1))
    d.right(i)
    d.circle(60,i)
    d.forward(i)
    d.left(100)
    d.backward(i)
    d.left(100)
    o += 0.05
screen.exitonclick()